### ISSUE TITLE
Question: Does this work for Collections?

### ISSUE THREAD

**Issue by Dhruvin-Purohit** [acollierr17/paginate#5]
So i wanted a paginator for my discord bot and i had to make one but i was using slice so collections were not supported, then randomly found this package but i don't know if this works or not can i get answer?

**Comment by acollierr17** [comment]
If you convert the collection to an array, you'll be able to use this package with that data type.

**Comment by Dhruvin-Purohit** [comment]
maybe add support for collections and/or objects too?

would be great because not every time a user would like to give array

**Comment by acollierr17** [comment]
That's definitely something I can consider! Also if anyone else is
tracking, you're free to open a PR about this issue.

**Comment by Dhruvin-Purohit** [comment]
Thanks
